# Pegar  vários comandos INSERT e transformar em um único comando multi-valorado
## ?reWriteBatchedInserts=true
spring.datasource.url=jdbc:postgresql://localhost:5432/tasks?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# Define o tamanho máximo permitido para o parâmetro 'size'
## spring.data.web.pageable.max-page-size=50
# Define o tamanho padrão caso o usuário não envie o parâmetro
spring.data.web.pageable.default-page-size=100
# melhor aproveitando do batch_size (organizar os comandos antes de submeter)
spring.jpa.properties.hibernate.order_inserts=true
# "segura" os comandos e os envia em um lote batch
spring.jpa.properties.hibernate.jdbc.batch_size=50
